Create roles table
rafaels549/subway-routes-api pull request #1
Opened 2024-08-30 17:55 UTC by rafaels549

2024-08-30 18:01 UTC, Luiz-Cruz commented on cli-config.php
> +$config = new PhpFile('migrations.php'); // Ou use um dos carregadores de Configuration\*
tem como remover os comentários desse arquivo?

2024-08-30 18:02 UTC, rafaels549 commented on cli-config.php
> +$config = new PhpFile('migrations.php'); // Ou use um dos carregadores de Configuration\*
Tem

2024-08-30 18:07 UTC, Luiz-Cruz requested changes

2024-08-30 18:07 UTC, Luiz-Cruz commented on migrations.php
> +
tem como essa configuração estar dentro da pasta db?

2024-08-30 18:07 UTC, Luiz-Cruz commented on cli-config.php
> +
esse arquivo serve para conectar no banco? 
seria interessante colocar em uma pasta do db

2024-08-30 18:07 UTC, Luiz-Cruz commented on src/Database/Seeds/SeedRoles.php
> +
esse arquivo ta com S maiusculo no seu nome, porém aqui não temos uma classe, tem algum motivo especifico do pq usar maisculo nesse arquivo?
algum padrão especifico de PHP?

2024-08-30 18:07 UTC, Luiz-Cruz commented on src/Database/Migrations/Version20240830010719.php
> +
Tem como o nome desse arquivo ter o um nome que dê mais contexto ?

CreateRolesTable

Algo assim?

Dessa forma visualmente conseguimos entender do que se trata.


Caso esteja gerando o arquivo de migration via terminal por algum comando, basta gerar de novo e colocar um nome para o arquivo da migration pelo proprio comando do ORM.

2024-08-30 18:07 UTC, Luiz-Cruz commented on cli-config.php
> +
e também seria interessante dar um nome que dê mais contexto a ele, 

cli-config.php não diz nada em especifico do que se trata... principalmente pelo fato de também estar fora de uma pasta.

2024-08-30 18:15 UTC, rafaels549 commented on src/Database/Seeds/SeedRoles.php
> +
Penso que seja Camel Case , ou tem nada a ver ?

2024-08-30 18:18 UTC, rafaels549 commented on migrations.php
> +
Beleza

2024-09-03 17:33 UTC, Luiz-Cruz requested changes

2024-09-03 17:33 UTC, Luiz-Cruz commented on src/Database/Database.php
> +
tem como remover essas linhas vazias?

2024-09-09 22:06 UTC, Luiz-Cruz requested changes

2024-09-09 22:06 UTC, Luiz-Cruz commented on src/Database/Migrations/CreateRolesTable.php
> +
apagar linhas vazias

2024-09-09 22:06 UTC, Luiz-Cruz commented on src/Database/Seeds/SeedRoles.php
> +// Criar as roles
remover comentário desnecessário

2024-09-09 22:06 UTC, Luiz-Cruz commented on src/Database/Database.php
> +?>
adicionar linha vazia no fim do arquivo

2024-09-09 22:06 UTC, Luiz-Cruz commented on src/Database/migration-config.php
> +
remover linha vazia

2024-09-09 22:06 UTC, Luiz-Cruz commented on src/Database/migration-config.php
> +
remover linha vazia

2024-09-09 22:06 UTC, Luiz-Cruz commented on src/Database/migrations.php
> +];
adicionar linha vazia ao fim do arquivo

2024-09-11 16:14 UTC, Luiz-Cruz requested changes

2024-09-11 16:14 UTC, Luiz-Cruz commented on src/Database/Database.php
> +}
não ta faltando a tag ?> 
fechando o arquivo?

2024-09-11 16:14 UTC, Luiz-Cruz commented on src/app.php
>  $app->run();
não ta faltando a tag ?> 
fechando o arquivo?

2024-09-11 16:14 UTC, Luiz-Cruz commented on src/Database/migration-config.php
> +
não ta faltando a tag ?> 
fechando o arquivo?

2024-09-11 16:14 UTC, Luiz-Cruz commented on src/Database/migration-config.php
> +
não ta faltando a tag ?> 
fechando o arquivo?

2024-09-11 16:14 UTC, Luiz-Cruz commented on src/Database/Seeds/SeedRoles.php
> +echo "Seed executed successfully.\n";
não ta faltando a tag ?> 
fechando o arquivo?

2024-09-11 16:22 UTC, Luiz-Cruz commented on src/Database/Migrations/CreateRolesTable.php
> +
ainda não foi alterado isso

2024-09-11 16:23 UTC, Luiz-Cruz commented on src/Database/Seeds/SeedRoles.php
> +
apagar linha vazia, deixa uma só

2024-09-11 16:23 UTC, Luiz-Cruz commented on src/Database/Seeds/SeedRoles.php
> +
apagar linha vazia, deixa uma só

2024-09-11 16:23 UTC, Luiz-Cruz commented on src/Database/Seeds/SeedRoles.php
> +
apagar linha vazia, deixa uma só

2024-09-11 16:24 UTC, Luiz-Cruz commented on .gitignore
> +
apagar linha vazia, deixa uma só

2024-09-11 17:47 UTC, merged