Feature/create user
rafaels549/subway-routes-api pull request #7
Opened 2024-10-14 16:05 UTC by rafaels549

**Description**

This pull request introduces a new POST route for user creation

[**Trello Item**](https://trello.com/c/GXOUH3IY/7-feature-users)

More information:

•⁠ ⁠[**Trello Project**](https://trello.com/b/DmOMRsSm/subway-routes-rafael)

2024-10-15 14:02 UTC, Luiz-Cruz requested changes
- Adicionar validação de dados mais robusta para campos como email, senha e data de nascimento.

- Implementar criptografia de senha com password_hash antes de salvar.

- Incluir blocos try-catch para tratar exceções ao criar instâncias de objetos, como new \DateTime.

- Envolver o flush() do EntityManager em um try-catch para capturar possíveis erros de banco de dados.

- Melhorar as mensagens de erro para retornar respostas mais claras (em inglês).

- Remover a validação de JSON da controller e movê-la para um middleware.

2024-10-15 14:02 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +                $response->getBody()->write(json_encode(['error' => 'JSON inválido']));
poderia colocar o texto de erro em inglês?

2024-10-15 14:02 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +                )
Embora o código valide se todos os campos obrigatórios estão presentes, não há uma validação mais profunda sobre o conteúdo dos dados. Por exemplo:

email: Deve ser validado se realmente é um e-mail válido.

date_of_birth: Não há verificação se a data está em um formato 
correto ou se a pessoa tem a idade mínima aceitável.

password: Não há verificação de requisitos mínimos, como tamanho ou complexidade.

Considerar o uso de bibliotecas de validação como o Respect/Validation para garantir que todos os campos tenham o formato correto.

2024-10-15 14:02 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +                )
É possível fazer a validação do JSON da request utilizando um middleware, o que vai melhorar a separação de responsabilidades e manter o código da controller mais limpo.

2024-10-15 14:02 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +            $entityManager->flush();
Durante a execução de algumas operações, como o flush() do EntityManager (que salva os dados no banco de dados) ou a criação de uma nova instância de \DateTime, podem ocorrer erros que lancem exceções. Esses erros podem ser gerados por diversas razões, como problemas de conexão com o banco de dados, dados incorretos no formato de data, entre outros.

Ao adicionar blocos try-catch`, você pode capturar essas exceções e tratar esses erros de maneira controlada, evitando que o código falhe completamente e fornecendo respostas mais claras ao usuário.


Daria para fazer algo como:

```
try {
    $roleId = Uuid::fromString($data['role_id']);
    $user = new User(
        $data['username'],
        password_hash($data['password'], PASSWORD_BCRYPT),
        $data['contact']['email'],
        $roleId,
        $data['contact']['phone'],
        $data['address']['street'],
        $data['address']['city'],
        $data['address']['country'],
        $data['address']['postal_code'],
        $data['address']['state'],
        new \DateTime($data['date_of_birth']),
        $data['gender'],
        $data['nationality'],
        $data['languages']
    );

    $entityManager->persist($user);
    $entityManager->flush();

    $response->getBody()->write(json_encode([
        'message' => 'Usuário criado com sucesso'
    ]));

    return $response->withStatus(201)->withHeader('Content-Type', 'application/json');

} catch (\Exception $e) {
    $response->getBody()->write(json_encode([
        'error' => 'Erro ao criar o usuário: ' . $e->getMessage()
    ]));
    return $response->withStatus(500)->withHeader('Content-Type', 'application/json');
}

```

2024-10-15 14:02 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +                $data['password'],
O código que você forneceu não está criptografando a senha. Atualmente, a senha está sendo recebida do corpo da requisição e sendo salva diretamente no banco de dados sem qualquer tipo de criptografia...

2024-10-17 03:43 UTC, Luiz-Cruz requested changes

2024-10-17 03:43 UTC, Luiz-Cruz commented on src/Middleware/UserValidationMiddleware.php
> +
remover linha vazia

2024-10-17 03:43 UTC, Luiz-Cruz commented on src/Middleware/UserValidationMiddleware.php
> +
remover linha vazia

2024-10-17 03:43 UTC, Luiz-Cruz commented on src/Middleware/UserValidationMiddleware.php
> +
remover linha vazia

2024-10-17 03:43 UTC, Luiz-Cruz commented on src/Middleware/UserValidationMiddleware.php
> +
o mesmo aqui

2024-10-17 03:43 UTC, Luiz-Cruz commented on src/Middleware/UserValidationMiddleware.php
> +        }
tem como ser em inglês todo tipo de comunicação do seu código?

2024-10-17 03:43 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +
remover linha vazia

2024-10-17 03:43 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +                $data['password'],
Com esse código atual, quando você executa a request pelo Insomnia, está sendo salva a senha criptografada no banco? poderia mandar uns exemplos aqui por favor?

2024-10-17 03:43 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +                $data['password'],
tenho a leve impressão de que estamos fazendo a validação da senha mas no final de tudo acabamos salvando a senha do body diretamente no banco e sem criptografia

2024-10-17 13:07 UTC, rafaels549 commented on src/Controllers/UserController.php
> +                $data['password'],
![Captura de tela 2024-10-17 100643](https://github.com/user-attachments/assets/be2792f7-08b1-4ff5-82f9-1d5a2eb6df2e)
![Captura de tela 2024-10-17 100643](https://github.com/user-attachments/assets/4e4c7671-fb01-420a-b157-4e6ba0404701)

2024-10-17 13:08 UTC, rafaels549 commented on src/Controllers/UserController.php
> +                $data['password'],
Aqui está a captura de tela do meu banco de dados , usando o gerenciador DBeaver, e foi salvo dessa maneira no banco

2024-10-17 13:09 UTC, rafaels549 commented on src/Middleware/UserValidationMiddleware.php
> +        }
Beleza

2024-10-17 13:20 UTC, rafaels549 commented on src/Controllers/UserController.php
> +                $data['password'],
https://github.com/user-attachments/assets/71872680-564e-4813-85f7-989130865632

2024-10-20 23:00 UTC, Luiz-Cruz commented on logs/app.log
Porque adicionar isso?

2024-10-20 23:05 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +
apagar linha vazia

2024-10-20 23:05 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +
apagar linha vazia

2024-10-20 23:05 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +
apagar linha vazia

2024-10-20 23:05 UTC, Luiz-Cruz commented on src/Controllers/UserController.php
> +
apagar linha vazia

2024-10-20 23:06 UTC, Luiz-Cruz commented on src/Database/Database.php
apagar linha vazia

2024-10-20 23:06 UTC, Luiz-Cruz commented on src/Database/Database.php
apagar linha vazia

2024-10-20 23:06 UTC, Luiz-Cruz commented on src/Database/Database.php
> +
apagar linha vazia

2024-10-20 23:07 UTC, Luiz-Cruz commented on src/Database/Database.php
apagar linha vazia

2024-10-20 23:07 UTC, Luiz-Cruz commented on src/Database/Database.php
> +
apagar linha vazia

2024-10-20 23:10 UTC, Luiz-Cruz requested changes
Adicionei alguns comentários relacionados a linhas vazias na revisão de 3 dias atrás, essas alterações ainda não foram feitas no código atual.

Para poder te auxiliar, indico que vá vendo esses comentários no PR e vá alterando, assim que realizar a alteração solicitada, deixe uma mensagem no comentário como "feito" e marque como resolvido o conflito, assim ele minimizará na conversa interna do PR.

2024-10-21 09:31 UTC, rafaels549 commented on logs/app.log
Para poder ver com mais detalhes os erros de log da aplicação , e ser mais eficiente para solucionar os erros

2024-10-23 02:52 UTC, Luiz-Cruz approved these changes

2024-10-23 09:05 UTC, merged